use_frameworks!

platform :ios, '11.0'

target 'JXSegmentedSeparatorDataSource_Example' do
  pod 'JXSegmentedSeparatorDataSource', :path => '../'

  target 'JXSegmentedSeparatorDataSource_Tests' do
    inherit! :search_paths

    
  end
end
